### ISSUE TITLE
Write access is allowed from event dispatch thread only

### ISSUE THREAD

**Issue by enerjazzer** [itechbear/CLion-MacroFormatter#4]
Hi,

the following exception is being thrown from your extension in CLion: 
"Write access is allowed from event dispatch thread only"
The stacktrace:
```stacktrace
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@797c7ffb
Current thread: Thread[ApplicationImpl pooled thread 204,4,Idea Thread Group] 2132374727
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 426179003
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:959)
	at com.intellij.openapi.application.impl.ApplicationImpl.startWrite(ApplicationImpl.java:1041)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:883)
	at com.intellij.psi.impl.PsiDocumentManagerBase.handleCommitWithoutPsi(PsiDocumentManagerBase.java:956)
	at com.intellij.psi.impl.PsiDocumentManagerBase.documentChanged(PsiDocumentManagerBase.java:858)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.documentChanged(PsiDocumentManagerImpl.java:84)
	at jdk.internal.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:130)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:24)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:88)
	at com.sun.proxy.$Proxy75.documentChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:899)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:803)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:668)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:615)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.lambda$promoteNonPhysicalChangesToDocument$0(PsiEventWrapperAspect.java:76)
	at com.intellij.psi.impl.PsiToDocumentSynchronizer.performAtomically(PsiToDocumentSynchronizer.java:126)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.promoteNonPhysicalChangesToDocument(PsiEventWrapperAspect.java:76)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.sendAfterEvents(PsiEventWrapperAspect.java:59)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.update(PsiEventWrapperAspect.java:52)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$null$1(PomModelImpl.java:177)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:564)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:191)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:135)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:149)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:596)
	at com.intellij.psi.formatter.FormatterUtil.addWhiteSpace(FormatterUtil.java:458)
	at com.intellij.psi.formatter.FormatterUtil.replaceWhiteSpace(FormatterUtil.java:350)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.lambda$replaceWithPsiInLeaf$1(PsiBasedFormattingModel.java:147)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.lambda$performActionWithFormatterDisabled$6(CodeStyleManagerImpl.java:696)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:108)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.lambda$performActionWithFormatterDisabled$8(CodeStyleManagerImpl.java:725)
	at com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:682)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:723)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:695)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWithPsiInLeaf(PsiBasedFormattingModel.java:146)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWithPSI(PsiBasedFormattingModel.java:109)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWhiteSpace(PsiBasedFormattingModel.java:67)
	at com.jetbrains.cidr.lang.formatting.OCPsiBasedFormattingModel.replaceWhiteSpace(OCPsiBasedFormattingModel.java:64)
	at com.intellij.formatting.engine.FormatProcessorUtils.replaceWhiteSpace(FormatProcessorUtils.java:45)
	at com.intellij.formatting.engine.ApplyChangesState.doIteration(ApplyChangesState.java:175)
	at com.intellij.formatting.engine.State.iteration(State.java:25)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:26)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:107)
	at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:705)
	at com.intellij.formatting.FormatterImpl.execute(FormatterImpl.java:274)
	at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:239)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processRange(CodeFormatterFacade.java:118)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processElement(CodeFormatterFacade.java:86)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:90)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:70)
	at com.jetbrains.cidr.lang.util.OCElementFactory.a(OCElementFactory.java:696)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.lambda$disablePostprocessFormattingInside$1(PostprocessReformattingAspect.java:100)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:108)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:99)
	at com.jetbrains.cidr.lang.util.OCElementFactory.codeFragment(OCElementFactory.java:695)
	at com.jetbrains.cidr.lang.util.OCElementFactory.codeFragment(OCElementFactory.java:655)
	at com.jetbrains.cidr.lang.util.OCElementFactory.typeCodeFragment(OCElementFactory.java:637)
	at com.jetbrains.cidr.lang.util.OCElementFactory.typeElementFromTextOrNull(OCElementFactory.java:555)
	at com.jetbrains.cidr.lang.util.OCElementFactory.typeElementFromText(OCElementFactory.java:550)
	at com.jetbrains.cidr.lang.util.OCDocUtil.getCanonicalName(OCDocUtil.java:157)
	at com.jetbrains.cidr.lang.util.OCDocUtil.getCanonicalPrefix(OCDocUtil.java:231)
	at com.jetbrains.cidr.lang.documentation.CidrDocumentationProvider.a(CidrDocumentationProvider.java:649)
	at com.jetbrains.cidr.lang.documentation.CidrDocumentationProvider.a(CidrDocumentationProvider.java:463)
	at com.jetbrains.cidr.lang.documentation.CidrDocumentationProvider.quickDocContent(CidrDocumentationProvider.java:296)
	at com.jetbrains.cidr.lang.documentation.CidrDocumentationProvider.getQuickNavigateInfo(CidrDocumentationProvider.java:86)
	at com.github.itechbear.macroformatter.provider.MacroDocumentationProvider.getQuickNavigateInfo(MacroDocumentationProvider.java:24)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.getQuickNavigateInfo(CompositeDocumentationProvider.java:112)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.generateInfo(CtrlMouseHandler.java:266)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$1000(CtrlMouseHandler.java:86)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$InfoSingle.getInfo(CtrlMouseHandler.java:386)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.doExecute(CtrlMouseHandler.java:697)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.lambda$execute$0(CtrlMouseHandler.java:673)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:286)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$null$3(NonBlockingReadActionImpl.java:255)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$null$4(NonBlockingReadActionImpl.java:255)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:825)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:62)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$5(NonBlockingReadActionImpl.java:254)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by itechbear** [comment]
Although this plugin has not been updated for a while, I'm glad to know there's someone still using it. I will spend some time updating it.

**Comment by enerjazzer** [comment]
Thank you for the plugin! I was surprised not seeing this functionality built-in in CLion, so your plugin is really useful.
There were a few more occurrences of this exception, one with a different stack trace:
```stacktrace
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@797c7ffb
Current thread: Thread[Alarm Pool,4,Idea Thread Group] 1908767930
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 426179003
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:959)
	at com.intellij.openapi.application.impl.ApplicationImpl.startWrite(ApplicationImpl.java:1041)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:883)
	at com.intellij.psi.impl.PsiDocumentManagerBase.handleCommitWithoutPsi(PsiDocumentManagerBase.java:956)
	at com.intellij.psi.impl.PsiDocumentManagerBase.documentChanged(PsiDocumentManagerBase.java:858)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.documentChanged(PsiDocumentManagerImpl.java:84)
	at jdk.internal.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:130)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:24)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:88)
	at com.sun.proxy.$Proxy75.documentChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:899)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:803)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:668)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:615)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.lambda$promoteNonPhysicalChangesToDocument$0(PsiEventWrapperAspect.java:76)
	at com.intellij.psi.impl.PsiToDocumentSynchronizer.performAtomically(PsiToDocumentSynchronizer.java:126)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.promoteNonPhysicalChangesToDocument(PsiEventWrapperAspect.java:76)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.sendAfterEvents(PsiEventWrapperAspect.java:59)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.update(PsiEventWrapperAspect.java:52)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$null$1(PomModelImpl.java:177)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:564)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:191)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:135)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:149)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:596)
	at com.intellij.psi.formatter.FormatterUtil.addWhiteSpace(FormatterUtil.java:458)
	at com.intellij.psi.formatter.FormatterUtil.replaceWhiteSpace(FormatterUtil.java:350)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.lambda$replaceWithPsiInLeaf$1(PsiBasedFormattingModel.java:147)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.lambda$performActionWithFormatterDisabled$6(CodeStyleManagerImpl.java:696)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:108)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.lambda$performActionWithFormatterDisabled$8(CodeStyleManagerImpl.java:725)
	at com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:682)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:723)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:695)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWithPsiInLeaf(PsiBasedFormattingModel.java:146)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWithPSI(PsiBasedFormattingModel.java:109)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWhiteSpace(PsiBasedFormattingModel.java:67)
	at com.jetbrains.cidr.lang.formatting.OCPsiBasedFormattingModel.replaceWhiteSpace(OCPsiBasedFormattingModel.java:64)
	at com.intellij.formatting.engine.FormatProcessorUtils.replaceWhiteSpace(FormatProcessorUtils.java:45)
	at com.intellij.formatting.engine.ApplyChangesState.doIteration(ApplyChangesState.java:175)
	at com.intellij.formatting.engine.State.iteration(State.java:25)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:26)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:107)
	at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:705)
	at com.intellij.formatting.FormatterImpl.execute(FormatterImpl.java:274)
	at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:239)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processRange(CodeFormatterFacade.java:118)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processElement(CodeFormatterFacade.java:86)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:90)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:70)
	at com.jetbrains.cidr.lang.util.OCElementFactory.a(OCElementFactory.java:696)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.lambda$disablePostprocessFormattingInside$1(PostprocessReformattingAspect.java:100)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:108)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:99)
	at com.jetbrains.cidr.lang.util.OCElementFactory.codeFragment(OCElementFactory.java:695)
	at com.jetbrains.cidr.lang.util.OCElementFactory.codeFragment(OCElementFactory.java:655)
	at com.jetbrains.cidr.lang.util.OCElementFactory.typeCodeFragment(OCElementFactory.java:637)
	at com.jetbrains.cidr.lang.util.OCElementFactory.typeElementFromTextOrNull(OCElementFactory.java:555)
	at com.jetbrains.cidr.lang.util.OCElementFactory.typeElementFromText(OCElementFactory.java:550)
	at com.jetbrains.cidr.lang.util.OCDocUtil.getCanonicalName(OCDocUtil.java:157)
	at com.jetbrains.cidr.lang.documentation.CidrDocumentationProvider.b(CidrDocumentationProvider.java:664)
	at com.jetbrains.cidr.lang.documentation.CidrDocumentationProvider.a(CidrDocumentationProvider.java:460)
	at com.jetbrains.cidr.lang.documentation.CidrDocumentationProvider.quickDocContent(CidrDocumentationProvider.java:296)
	at com.jetbrains.cidr.lang.documentation.CidrDocumentationProvider.a(CidrDocumentationProvider.java:817)
	at com.jetbrains.cidr.lang.documentation.CidrDocumentationProvider.generateDocInnerHtml(CidrDocumentationProvider.java:802)
	at com.github.itechbear.macroformatter.provider.MacroDocumentationProvider.generateDocInnerHtml(MacroDocumentationProvider.java:63)
	at com.jetbrains.cidr.lang.documentation.CidrDocumentationProvider.generateDoc(CidrDocumentationProvider.java:108)
	at com.github.itechbear.macroformatter.provider.MacroDocumentationProvider.generateDoc(MacroDocumentationProvider.java:37)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:136)
	at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector.lambda$getDocumentation$2(DocumentationManager.java:1170)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:73)
	at com.intellij.codeInsight.documentation.QuickDocUtil.runInReadActionWithWriteActionPriorityWithRetries(QuickDocUtil.java:93)
	at com.intellij.codeInsight.documentation.QuickDocUtil.runInReadActionWithWriteActionPriorityWithRetries(QuickDocUtil.java:114)
	at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector.getDocumentation(DocumentationManager.java:1166)
	at com.intellij.codeInsight.documentation.DocumentationManager.lambda$doFetchDocInfo$14(DocumentationManager.java:811)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:371)
	at com.intellij.util.Alarm$Request.run(Alarm.java:358)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:217)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Hope this helps

**Comment by itechbear** [comment]
Hi, I just released the latest version for CLion 2019.3. I tested it on my windows machine and it worked without any problem. Can you please test it on your side?

Meanwhile, if you're not using CLion 2019.3, you can clone this repository, update CLion version in the gradle.properties file located at the root and use Gradle to build it for an older version of CLion.

**Comment by enerjazzer** [comment]
Hi, looks like at the JetBrains plugin page it's still the old 0.4.1?

**Comment by itechbear** [comment]
I didn't updated it in the plugin center. Wanted to make sure that it works before updating it. You can find it in the [CLion-MacroFormatter/Releases](https://github.com/itechbear/CLion-MacroFormatter/releases) tab.
